[package]
version = "0.1.0"
name = "ws_graph"
edition = "2021"
publish = false

[dependencies]
actix-web = "4.1"
dataloader = "0.15"
juniper = "0.15"
juniper_actix = "0.4"
log = "0.4"
chrono = { version = "0.4", features = ["serde"] }

ws_sql = { path = "../sql" }